---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - metrics.k8s.io.example.com
  resources:
  - nodemetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.k8s.io.example.com
  resources:
  - nodemetrics/finalizers
  verbs:
  - update
- apiGroups:
  - metrics.k8s.io.example.com
  resources:
  - nodemetrics/status
  verbs:
  - get
  - patch
  - update
